### ISSUE TITLE
Replace ejecting cube for a time with ejecting until we don't have a cube

### ISSUE THREAD

**Issue by Kassaba** [errorcodexero/robotdev#16]

**Comment by 1425** [comment]
We might want to temper this somewhat by having a minimum amount of time to eject so that if something goes wrong with the sensor we can still eject in the same way.  (There might be a switch that would make this not important anyway though - someone who knows should make sure they think through this).

**Comment by macovskym** [comment]
This should now be done.

**Comment by Kassaba** [comment]
I believe we wanted to make sure the logic was solid behind this because we don't want to not eject for long enough because the sensor doesn't think we have a cube. Maybe make sure that we don't see a cube for 1 second or so before declaring that we don't have a cube and stopping the belts?

**Comment by macovskym** [comment]
You're right, the new cube logic has not yet been added to the eject code.

**Comment by macovskym** [comment]
I've just added it, please try ejecting and dropping tonight and leave a comment with the results.

**Comment by Kassaba** [comment]
Butch made the logic the same for the autonomous code. Both are tested and look good. Ready to close.

**Comment by sjcbulldog** [comment]
This is working as expected and is in both auto and teleop.
