### ISSUE TITLE
Collector Dropping

### ISSUE THREAD

**Issue by tcavarno** [errorcodexero/robotdev#19]
Sometimes while executing other actions the cube sensor will detect and cause the collector to drive to the exchange height.

**Comment by Kassaba** [comment]
We believe that the sensor is losing sight of the cube then regaining sight of it, causing it to travel to exchange height. A possible fix is to make it so that it only travels to exchange height (after collecting a cube) if we are lower than exchange height when we detect a cube. We probably want this anyway in case we decide to collect off the top of the stack and we don't want our collector jamming down into the bottom of the stack.

**Comment by sjcbulldog** [comment]
We have a fix we just need to test. Basically the logic is that when a cube present sensor is detected it must remain true for 250ms to be valid. At that time we move the lift to exchange height only if it is near the floor and if calibration has happened.  Otherwise we do not move it.  If we have a cube and we detect the cube missing, it must stay missing for 500 ms to be valid and cause us to move to the no cube state.  We still don’t move the lift in the no cube state.

**Comment by Kassaba** [comment]
Are we ready to close this issue? It appears as though we have tested and verified that this is no longer a problem.

**Comment by sjcbulldog** [comment]
I want to look at why it moves to exchange height before calibration while in teleop.  I was able to look closely enough to see the new logic for this issue is working, but the lifter is telling us it is calibrated when we nave not done calibration.

**Comment by sjcbulldog** [comment]
This issue is closed, we fixed the bug with moving to exchange height when it was not calibrated.
