### ISSUE TITLE
Collector dropping at start of autonomous can be streamline

### ISSUE THREAD

**Issue by sjcbulldog** [errorcodexero/robotdev#47]
When we start an autonomous mode, we start with the collector folded into the robot.  In order the steps we take are ...

- Calibrate Lifter
- Calibrate Grabber
- Raise Lifter to Exchange Height (to drop collector)
- Lower Lifter to Floor Height
- Start Lifter to Exchange
- Start Driving
- etc.

The original intent was to free the collector and then calibration.  However, since we now calibrate with the collector folded into the robot, we don't need to ever go back to the floor with the collector.  This will shorten the auto mode startup sequence by a few hundred milliseconds and gives us one less step that might go wrong.

**Comment by Kassaba** [comment]
My one concern with this is that the cube may be more prone to falling out because when the collector drops down, the cube normally hits the ground. However, it will now be suspended in the air as the collector is quickly falling then stops all of a sudden as the grabber reaches its hard stop. We will need to test this.

**Comment by Kassaba** [comment]
Ready to close?
